name: CI - El Filtro de Desarrollo

on:
  push:
    branches:
      - feature-dev

jobs:
  build-test:
    name: Compilar y Pasar Tests
    runs-on: ubuntu-latest

    steps:
      - name: Descargar el código fuente
        uses: actions/checkout@v4

      - name: Configurar Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'

      - name: Compilar y ejecutar tests con Maven
        run: mvn test