name: CI - Limpieza y Silencio (Modo Batch)

on:
  push:

jobs:
  build-test:
    name: Limpiar, Compilar y Pasar Tests
    runs-on: ubuntu-latest

    steps:
      - name: Descargar el código fuente
        uses: actions/checkout@v4

      - name: Configurar Java 21 (Zulu)
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'

      - name: Limpiar y ejecutar tests en modo batch
        run: mvn -B clean test